- name: Create an AWX Instance
  community.kubernetes.k8s:
    state: present
    context: "{{ kubernetes_context }}"
    definition:
      apiVersion: awx.ansible.com/v1beta1
      kind: AWX
      metadata:
        name: awx
        namespace: "{{ kubernetes_namespace }}"
      spec:
        deployment_type: awx
        tower_admin_user: "{{ tower_admin_user | default('test') }}"
        tower_admin_email: "{{ tower_admin_email | default('test@example.com') }}"
        tower_admin_password: "{{ tower_admin_password | default('changeme') }}"
        tower_broadcast_websocket_secret: "{{ tower_broadcast_websocket_secret | default('changeme') }}"
        tower_ingress_type: Ingress
        tower_hostname: "{{ tower_hostname | default('awx.mycompany.com') }}"

- name: Patch the awx-service type
  community.kubernetes.k8s:
    state: present
    context: "{{ kubernetes_context }}"
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: awx-service
        namespace: "{{ kubernetes_namespace }}"
      spec:
        type: "{{ tower_web_svc_type }}"
