---
- name: awx-ops/ansible/droplet
  hosts: database
  gather_facts: no
  become: no

  tasks:

    - name: Include the droplet/database role
      include_role:
        name: droplet
        tasks_from: database.yml
      vars:
        awx_database_port: "{{ lookup('env', 'AWX_DATABASE_PORT') }}"
        awx_database_database: "{{ lookup('env', 'AWX_DATABASE_DATABASE') }}"
        awx_database_username: "{{ lookup('env', 'AWX_DATABASE_USERNAME') }}"
        awx_database_password: "{{ lookup('env', 'AWX_DATABASE_PASSWORD') }}"
