---
- name: awx-ops/ansible/kubernetes
  hosts: localhost
  connection: local
  gather_facts: no
  become: no

  tasks:

    - name: Include the kubernetes/awx-operator role
      include_role:
        name: kubernetes
        tasks_from: awx-operator.yml
      vars:
        kubernetes_context: "{{ lookup('env', 'K8S_CONTEXT') }}"
        kubernetes_namespace: "{{ lookup('env', 'K8S_NAMESPACE') }}"

    - name: Include the kubernetes/awx-instance role
      include_role:
        name: kubernetes
        tasks_from: awx-instance.yml
      vars:
        kubernetes_context: "{{ lookup('env', 'K8S_CONTEXT') }}"
        kubernetes_namespace: "{{ lookup('env', 'K8S_NAMESPACE') }}"
        tower_admin_user: "{{ lookup('env', 'AWX_ADMIN_USER') }}"
        tower_admin_email: "{{ lookup('env', 'AWX_ADMIN_EMAIL') }}"
        tower_admin_password: "{{ lookup('env', 'AWX_ADMIN_PASSWORD') }}"
        tower_broadcast_websocket_secret: "{{ lookup('env', 'AWX_WEBSOCKET_SECRET') }}"
        tower_hostname: "{{ lookup('env', 'AWX_HOSTNAME') }}"
        tower_task_image: "{{ lookup('env', 'AWX_WEB_IMAGE') }}"
        tower_web_image: "{{ lookup('env', 'AWX_WEB_IMAGE') }}"
        tower_web_svc_type: "{{ lookup('env', 'AWX_WEB_SVC_TYPE') }}"
        awx_database_host: "{{ hostvars['localhost']['groups']['database'][0] }}"
        awx_database_port: "{{ lookup('env', 'AWX_DATABASE_PORT') }}"
        awx_database_database: "{{ lookup('env', 'AWX_DATABASE_DATABASE') }}"
        awx_database_username: "{{ lookup('env', 'AWX_DATABASE_USERNAME') }}"
        awx_database_password: "{{ lookup('env', 'AWX_DATABASE_PASSWORD') }}"
