---
- name: awx-ops/ansible/kubernetes
  hosts: localhost
  connection: local
  gather_facts: no
  become: no

  vars_prompt:

    - name: p_kubernetes_context
      prompt: Kubernetes context
      private: no
      default: "{{ lookup('env', 'K8S_CONTEXT') }}"

    - name: p_kubernetes_namespace
      prompt: Kubernetes namespace (for AWX things)
      private: no
      default: "{{ lookup('env', 'K8S_NAMESPACE') }}"

    - name: p_tower_admin_user
      prompt: Username of the Tower admin
      private: no
      default: admin

    - name: p_tower_admin_email
      prompt: Email address of the Tower admin
      private: no
      default: admin@example.com

    - name: p_tower_admin_password
      prompt: Password of the Tower admin
      private: yes
      default: supersecretpassword123!!!

    - name: p_tower_broadcast_websocket_secret
      prompt: Secret of the Tower broadcast websocket
      private: yes
      default: supersecretpassword123!!!

    - name: p_tower_hostname
      prompt: Hostname of the Tower instance (Ingress)
      private: no
      default: awx.example.com

    - name: p_tower_task_image
      prompt: Tower task image version/tag
      private: no
      default: ansible/awx:15.0.0

    - name: p_tower_web_image
      prompt: Tower web image version/tag
      private: no
      default: ansible/awx:15.0.0

    - name: p_tower_web_svc_type
      prompt: Tower web service type (ClusterIP, LoadBalancer, etc)
      private: no
      default: LoadBalancer

  tasks:

    - name: Include the kubernetes/awx-operator role
      include_role:
        name: kubernetes
        tasks_from: awx-operator.yml
      vars:
        kubernetes_context: "{{ p_kubernetes_context }}"
        kubernetes_namespace: "{{ p_kubernetes_namespace }}"

    - name: Include the kubernetes/awx-instance role
      include_role:
        name: kubernetes
        tasks_from: awx-instance.yml
      vars:
        kubernetes_context: "{{ p_kubernetes_context }}"
        kubernetes_namespace: "{{ p_kubernetes_namespace }}"
        tower_admin_user: "{{ p_tower_admin_user }}"
        tower_admin_email: "{{ p_tower_admin_email }}"
        tower_admin_password: "{{ p_tower_admin_password }}"
        tower_broadcast_websocket_secret: "{{ p_tower_broadcast_websocket_secret }}"
        tower_hostname: "{{ p_tower_hostname }}"
        tower_task_image: "{{ p_tower_task_image }}"
        tower_web_image: "{{ p_tower_web_image }}"
        tower_web_svc_type: "{{ p_tower_web_svc_type }}"
